apiVersion: v1
kind: Pod
metadata:vi 
   name: simple-webapp-color-bleue
   labels:
    app: web
spec:
  containers:
  - name: web
    image: mmumshad/simple-webapp-color
    ports:
     - containerPort: 8080
    env:
     - name: APP_COLOR
       value: bleue
